### PR TITLE
utf8 identical checking

### PR DESCRIPTION
**Pull request by chenkovsky**
File.binread returns string with ASCII-8BIT encoding. but the rendered result is Utf8 encoding. For non-ascii characters, although the content is same, the comparison will return false. when we invoke migration generate with force option. it will delete the old migration file, and create a new migration file with the same content.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@chenkovsky Can we add a test for this change, so it doesn't break again in the future?

**Comment by chenkovsky** [comment]
@deivid-rodriguez I change the test. add utf8 character to content.

**Comment by deivid-rodriguez** [comment]
Sorry for dropping the ball here.

For the test, I would personally prefer a new separate test that uses UTF-8 content, rather that changing every test to create a file with UTF-8 content.

Other than that this PR looks good to me.

**Comment by Nytorian** [comment]
Heyy, just a little suggestion from me:

How about introducing a 'wrapper' method for `File.binread(destination)` and similar that output the earlier mentioned `ASCII-8BIT`? Ideally, we could force the output of `binread` to `Encoding.default_external` which would be more flexible for sure.

Regards

**Comment by rafaelfranca** [comment]
Closed by #786

**Pull request closed without merging**
