### PR TITLE
force keeping spaces

### PR DESCRIPTION
**Pull request by tonytonyjan**
ref: erikhuda/thor#398

### CODE REVIEW

**Comment by ImaginateWayne** [comment]
Do you know when and what version this change will be merged into? It would be a very useful change I've just hit the issue when I tried to create a formatter long_desc.

**Comment by tonytonyjan** [comment]
@ImaginateWayne  I have no idea. I am also wondering if this pull request did solve the problem.

**Comment by snowe2010** [comment]
Is this ever going to get merged?

**Comment by rafaelfranca** [comment]
Without tests, no, unless someone wants to write it.

**Comment by rafaelfranca** [comment]
Closing since no tests were added.

**Pull request closed without merging**
